# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/asus/Z00xD/setup-makefiles.sh

# Pick up overlay for features that depend on non-open-source files

LOCAL_PATH := $(call my-dir)

DEVICE_PACKAGE_OVERLAYS += vendor/asus/Z00xD/overlay

# Camera
PRODUCT_COPY_FILES += \
	vendor/asus/Z00xD/proprietary/bin/ZE500KG_afCali:system/bin/ZE500KG_afCali

# Power
PRODUCT_COPY_FILES += \
  vendor/asus/Z00xD/proprietary/bin/vm_bms:system/bin/vm_bms

# Sensor
PRODUCT_COPY_FILES += \
	vendor/asus/Z00xD/proprietary/bin/akmd09911:system/bin/akmd09911\
	vendor/asus/Z00xD/proprietary/lib/hw/sensors.AKM.msm8916.so:system/lib/hw/sensors.AKM.msm8916.so\
	vendor/asus/Z00xD/proprietary/lib/hw/sensors.msm8916.so:system/lib/hw/sensors.msm8916.so\
	vendor/asus/Z00xD/proprietary/lib/hw/sensors.PS_ALS.msm8916.so:system/lib/hw/sensors.PS_ALS.msm8916.so\
	vendor/asus/Z00xD/proprietary/lib64/hw/sensors.AKM.msm8916.so:system/lib64/hw/sensors.AKM.msm8916.so\
	vendor/asus/Z00xD/proprietary/lib64/hw/sensors.msm8916.so:system/lib64/hw/sensors.msm8916.so\
	vendor/asus/Z00xD/proprietary/lib64/hw/sensors.PS_ALS.msm8916.so:system/lib64/hw/sensors.PS_ALS.msm8916.so\
	vendor/asus/Z00xD/proprietary/vendor/lib/libcalmodule_gyroscope.so:system/vendor/lib/libcalmodule_gyroscope.so\
	vendor/asus/Z00xD/proprietary/vendor/lib64/libcalmodule_gyroscope.so:system/vendor/lib64/libcalmodule_gyroscope.so\
	vendor/asus/Z00xD/proprietary/lib/libcmdthread.so:system/lib/libcmdthread.so\
	vendor/asus/Z00xD/proprietary/lib64/libcmdthread.so:system/lib64/libcmdthread.so\
	vendor/asus/Z00xD/proprietary/etc/sensors/hals.conf:system/etc/sensors/hals.conf\
	vendor/asus/Z00xD/proprietary/vendor/etc/calmodule.cfg:system/vendor/etc/calmodule.cfg

# DRM
PRODUCT_COPY_FILES += \
	vendor/asus/Z00xD/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so\
	vendor/asus/Z00xD/proprietary/vendor/lib64/libQSEEComAPI.so:system/vendor/lib64/libQSEEComAPI.so

# Firmware
PRODUCT_COPY_FILES += \
	vendor/asus/Z00xD/proprietary/etc/firmware/keymaster.b00:system/etc/firmware/keymaster.b00\
	vendor/asus/Z00xD/proprietary/etc/firmware/keymaster.b01:system/etc/firmware/keymaster.b01\
	vendor/asus/Z00xD/proprietary/etc/firmware/keymaster.b02:system/etc/firmware/keymaster.b02\
	vendor/asus/Z00xD/proprietary/etc/firmware/keymaster.b03:system/etc/firmware/keymaster.b03\
	vendor/asus/Z00xD/proprietary/etc/firmware/keymaster.mdt:system/etc/firmware/keymaster.mdt\
	vendor/asus/Z00xD/proprietary/etc/firmware/wcnss.b00:system/etc/firmware/wcnss.b00\
	vendor/asus/Z00xD/proprietary/etc/firmware/wcnss.b01:system/etc/firmware/wcnss.b01\
	vendor/asus/Z00xD/proprietary/etc/firmware/wcnss.b02:system/etc/firmware/wcnss.b02\
	vendor/asus/Z00xD/proprietary/etc/firmware/wcnss.b04:system/etc/firmware/wcnss.b04\
	vendor/asus/Z00xD/proprietary/etc/firmware/wcnss.b06:system/etc/firmware/wcnss.b06\
	vendor/asus/Z00xD/proprietary/etc/firmware/wcnss.b09:system/etc/firmware/wcnss.b09\
	vendor/asus/Z00xD/proprietary/etc/firmware/wcnss.b10:system/etc/firmware/wcnss.b10\
	vendor/asus/Z00xD/proprietary/etc/firmware/wcnss.b11:system/etc/firmware/wcnss.b11\
	vendor/asus/Z00xD/proprietary/etc/firmware/wcnss.mdt:system/etc/firmware/wcnss.mdt

$(call inherit-product, vendor/asus/msm8916-common/msm8916-common-vendor.mk)
