PRODUCT_COPY_FILES += \
    vendor/asus/Z010D/proprietary/bin/qmi-framework-tests/check_system_health:system/bin/qmi-framework-tests/check_system_health\
    vendor/asus/Z010D/proprietary/bin/qmi-framework-tests/qmi_test_mt_client_init_instance:system/bin/qmi-framework-tests/qmi_test_mt_client_init_instance\
    vendor/asus/Z010D/proprietary/bin/AsusCommandSpecial:system/bin/AsusCommandSpecial\
    vendor/asus/Z010D/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon\
    vendor/asus/Z010D/proprietary/bin/btnvtool:system/bin/btnvtool\
    vendor/asus/Z010D/proprietary/bin/diag_callback_client:system/bin/diag_callback_client\
    vendor/asus/Z010D/proprietary/bin/diag_dci_sample:system/bin/diag_dci_sample\
    vendor/asus/Z010D/proprietary/bin/diag_klog:system/bin/diag_klog\
    vendor/asus/Z010D/proprietary/bin/diag_mdlog:system/bin/diag_mdlog\
    vendor/asus/Z010D/proprietary/bin/diag_qshrink4_daemon:system/bin/diag_qshrink4_daemon\
    vendor/asus/Z010D/proprietary/bin/diag_socket_log:system/bin/diag_socket_log\
    vendor/asus/Z010D/proprietary/bin/diag_uart_log:system/bin/diag_uart_log\
    vendor/asus/Z010D/proprietary/bin/ftmdaemon:system/bin/ftmdaemon\
    vendor/asus/Z010D/proprietary/bin/fw_auto_update:system/bin/fw_auto_update\
    vendor/asus/Z010D/proprietary/bin/fw_man_update:system/bin/fw_man_update\
    vendor/asus/Z010D/proprietary/bin/GammaSetting:system/bin/GammaSetting\
    vendor/asus/Z010D/proprietary/bin/garden_app:system/bin/garden_app\
    vendor/asus/Z010D/proprietary/bin/gpsone_daemon:system/bin/gpsone_daemon\
    vendor/asus/Z010D/proprietary/bin/hal_proxy_daemon:system/bin/hal_proxy_daemon\
    vendor/asus/Z010D/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init\
    vendor/asus/Z010D/proprietary/bin/hostapd:system/bin/hostapd\
    vendor/asus/Z010D/proprietary/bin/hostapd_cli:system/bin/hostapd_cli\
    vendor/asus/Z010D/proprietary/bin/IR_sensor_module_number:system/bin/IR_sensor_module_number\
    vendor/asus/Z010D/proprietary/bin/is_keybox_valid:system/bin/is_keybox_valid\
    vendor/asus/Z010D/proprietary/bin/iwlist:system/bin/iwlist\
    vendor/asus/Z010D/proprietary/bin/LedTest:system/bin/LedTest\
    vendor/asus/Z010D/proprietary/bin/lightsensor_calibration_start:system/bin/lightsensor_calibration_start\
    vendor/asus/Z010D/proprietary/bin/loc_launcher:system/bin/loc_launcher\
    vendor/asus/Z010D/proprietary/bin/mm-audio-ftm:system/bin/mm-audio-ftm\
    vendor/asus/Z010D/proprietary/bin/mm-qjpeg-dec-test:system/bin/mm-qjpeg-dec-test\
    vendor/asus/Z010D/proprietary/bin/mm-qjpeg-enc-test:system/bin/mm-qjpeg-enc-test\
    vendor/asus/Z010D/proprietary/bin/mm-qomx-idec-test:system/bin/mm-qomx-idec-test\
    vendor/asus/Z010D/proprietary/bin/mm-qomx-ienc-test:system/bin/mm-qomx-ienc-test\
    vendor/asus/Z010D/proprietary/bin/mm-vidc-omx-test:system/bin/mm-vidc-omx-test\
    vendor/asus/Z010D/proprietary/bin/msm_irqbalance:system/bin/msm_irqbalance\
    vendor/asus/Z010D/proprietary/bin/msm-vidc-test:system/bin/msm-vidc-test\
    vendor/asus/Z010D/proprietary/bin/netmgrd:system/bin/netmgrd\
    vendor/asus/Z010D/proprietary/bin/nl_listener:system/bin/nl_listener\
    vendor/asus/Z010D/proprietary/bin/oemwvtest:system/bin/oemwvtest\
    vendor/asus/Z010D/proprietary/bin/onFgAppChanged:system/bin/onFgAppChanged\
    vendor/asus/Z010D/proprietary/bin/ProximityCalibration:system/bin/ProximityCalibration\
    vendor/asus/Z010D/proprietary/bin/proximity_calibration_start:system/bin/proximity_calibration_start\
    vendor/asus/Z010D/proprietary/bin/proximity_poll_get_proxm:system/bin/proximity_poll_get_proxm\
    vendor/asus/Z010D/proprietary/bin/qcom-system-daemon:system/bin/qcom-system-daemon\
    vendor/asus/Z010D/proprietary/bin/qmi_simple_ril_test:system/bin/qmi_simple_ril_test\
    vendor/asus/Z010D/proprietary/bin/qmuxd:system/bin/qmuxd\
    vendor/asus/Z010D/proprietary/bin/qseecomd:system/bin/qseecomd\
    vendor/asus/Z010D/proprietary/bin/qseecom_sample_client:system/bin/qseecom_sample_client\
    vendor/asus/Z010D/proprietary/bin/radish:system/bin/radish\
    vendor/asus/Z010D/proprietary/bin/RestoreCalibrationData:system/bin/RestoreCalibrationData\
    vendor/asus/Z010D/proprietary/bin/rfs_access:system/bin/rfs_access\
    vendor/asus/Z010D/proprietary/bin/rmt_storage:system/bin/rmt_storage\
    vendor/asus/Z010D/proprietary/bin/tbaseLoader:system/bin/tbaseLoader\
    vendor/asus/Z010D/proprietary/bin/test_ispCali_Android_L:system/bin/test_ispCali_Android_L\
    vendor/asus/Z010D/proprietary/bin/tftp_server:system/bin/tftp_server\
    vendor/asus/Z010D/proprietary/bin/time_daemon:system/bin/time_daemon\
    vendor/asus/Z010D/proprietary/bin/touch_fw_update:system/bin/touch_fw_update\
    vendor/asus/Z010D/proprietary/bin/touch_node_authority.sh:system/bin/touch_node_authority.sh\
    vendor/asus/Z010D/proprietary/bin/touch_self_test:system/bin/touch_self_test\
    vendor/asus/Z010D/proprietary/bin/wdsdaemon:system/bin/wdsdaemon\
    vendor/asus/Z010D/proprietary/bin/wfdservice:system/bin/wfdservice\
    vendor/asus/Z010D/proprietary/bin/widevine.sh:system/bin/widevine.sh\
    vendor/asus/Z010D/proprietary/bin/xtwifi-client:system/bin/xtwifi-client\
    vendor/asus/Z010D/proprietary/bin/xtwifi-inet-agent:system/bin/xtwifi-inet-agent\
    vendor/asus/Z010D/proprietary/bin/yepdiag:system/bin/yepdiag

PRODUCT_COPY_FILES += \
    vendor/asus/Z010D/proprietary/etc/cne/andsfCne.xml:system/etc/cne/andsfCne.xml\
    vendor/asus/Z010D/proprietary/etc/cne/SwimConfig.xml:system/etc/cne/SwimConfig.xml\
    vendor/asus/Z010D/proprietary/etc/dpm/nsrm/NsrmConfiguration.xml:system/etc/dpm/nsrm/NsrmConfiguration.xml\
    vendor/asus/Z010D/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_C01.txt:system/etc/firmware/phone_ct/LUT_C01.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_C02.txt:system/etc/firmware/phone_ct/LUT_C02.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_C03.txt:system/etc/firmware/phone_ct/LUT_C03.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_C04.txt:system/etc/firmware/phone_ct/LUT_C04.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_C05.txt:system/etc/firmware/phone_ct/LUT_C05.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_C06.txt:system/etc/firmware/phone_ct/LUT_C06.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_C07.txt:system/etc/firmware/phone_ct/LUT_C07.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_C08.txt:system/etc/firmware/phone_ct/LUT_C08.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_C09.txt:system/etc/firmware/phone_ct/LUT_C09.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_C10.txt:system/etc/firmware/phone_ct/LUT_C10.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_DEF.txt:system/etc/firmware/phone_ct/LUT_DEF.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_Rd01.txt:system/etc/firmware/phone_ct/LUT_Rd01.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_Rd02.txt:system/etc/firmware/phone_ct/LUT_Rd02.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_Rd03.txt:system/etc/firmware/phone_ct/LUT_Rd03.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_RdStrong.txt:system/etc/firmware/phone_ct/LUT_RdStrong.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_RdWeak.txt:system/etc/firmware/phone_ct/LUT_RdWeak.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_W01.txt:system/etc/firmware/phone_ct/LUT_W01.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_W02.txt:system/etc/firmware/phone_ct/LUT_W02.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_W03.txt:system/etc/firmware/phone_ct/LUT_W03.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_W04.txt:system/etc/firmware/phone_ct/LUT_W04.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_W05.txt:system/etc/firmware/phone_ct/LUT_W05.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_W06.txt:system/etc/firmware/phone_ct/LUT_W06.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_W07.txt:system/etc/firmware/phone_ct/LUT_W07.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_W08.txt:system/etc/firmware/phone_ct/LUT_W08.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_W09.txt:system/etc/firmware/phone_ct/LUT_W09.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/phone_ct/LUT_W10.txt:system/etc/firmware/phone_ct/LUT_W10.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/Splendid/LUT/LUT_Rd03.txt:system/etc/firmware/Splendid/LUT/LUT_Rd03.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/wlan/prima/WCNSS_cfg.dat:system/etc/firmware/wlan/prima/WCNSS_cfg.dat\
    vendor/asus/Z010D/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini:system/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini\
    vendor/asus/Z010D/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin:system/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin\
    vendor/asus/Z010D/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw\
    vendor/asus/Z010D/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw\
    vendor/asus/Z010D/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw\
    vendor/asus/Z010D/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw\
    vendor/asus/Z010D/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw\
    vendor/asus/Z010D/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw\
    vendor/asus/Z010D/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw\
    vendor/asus/Z010D/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw\
    vendor/asus/Z010D/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw\
    vendor/asus/Z010D/proprietary/etc/firmware/cmnlib.b00:system/etc/firmware/cmnlib.b00\
    vendor/asus/Z010D/proprietary/etc/firmware/cmnlib.b01:system/etc/firmware/cmnlib.b01\
    vendor/asus/Z010D/proprietary/etc/firmware/cmnlib.b02:system/etc/firmware/cmnlib.b02\
    vendor/asus/Z010D/proprietary/etc/firmware/cmnlib.b03:system/etc/firmware/cmnlib.b03\
    vendor/asus/Z010D/proprietary/etc/firmware/cmnlib.mdt:system/etc/firmware/cmnlib.mdt\
    vendor/asus/Z010D/proprietary/etc/firmware/ice40.bin:system/etc/firmware/ice40.bin\
    vendor/asus/Z010D/proprietary/etc/firmware/keymaster.b00:system/etc/firmware/keymaster.b00\
    vendor/asus/Z010D/proprietary/etc/firmware/keymaster.b01:system/etc/firmware/keymaster.b01\
    vendor/asus/Z010D/proprietary/etc/firmware/keymaster.b02:system/etc/firmware/keymaster.b02\
    vendor/asus/Z010D/proprietary/etc/firmware/keymaster.b03:system/etc/firmware/keymaster.b03\
    vendor/asus/Z010D/proprietary/etc/firmware/keymaster.mdt:system/etc/firmware/keymaster.mdt\
    vendor/asus/Z010D/proprietary/etc/firmware/nfc_test.bin:system/etc/firmware/nfc_test.bin\
    vendor/asus/Z010D/proprietary/etc/firmware/Phone_vivid.txt:system/etc/firmware/Phone_vivid.txt\
    vendor/asus/Z010D/proprietary/etc/firmware/Signedrompatch_v20.bin:system/etc/firmware/Signedrompatch_v20.bin\
    vendor/asus/Z010D/proprietary/etc/firmware/Signedrompatch_v21.bin:system/etc/firmware/Signedrompatch_v21.bin\
    vendor/asus/Z010D/proprietary/etc/firmware/Signedrompatch_v24.bin:system/etc/firmware/Signedrompatch_v24.bin\
    vendor/asus/Z010D/proprietary/etc/firmware/Signedrompatch_v30.bin:system/etc/firmware/Signedrompatch_v30.bin\
    vendor/asus/Z010D/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00\
    vendor/asus/Z010D/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01\
    vendor/asus/Z010D/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02\
    vendor/asus/Z010D/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03\
    vendor/asus/Z010D/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04\
    vendor/asus/Z010D/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt\
    vendor/asus/Z010D/proprietary/etc/firmware/wcnss.b00:system/etc/firmware/wcnss.b00\
    vendor/asus/Z010D/proprietary/etc/firmware/wcnss.b01:system/etc/firmware/wcnss.b01\
    vendor/asus/Z010D/proprietary/etc/firmware/wcnss.b02:system/etc/firmware/wcnss.b02\
    vendor/asus/Z010D/proprietary/etc/firmware/wcnss.b04:system/etc/firmware/wcnss.b04\
    vendor/asus/Z010D/proprietary/etc/firmware/wcnss.b06:system/etc/firmware/wcnss.b06\
    vendor/asus/Z010D/proprietary/etc/firmware/wcnss.b09:system/etc/firmware/wcnss.b09\
    vendor/asus/Z010D/proprietary/etc/firmware/wcnss.b10:system/etc/firmware/wcnss.b10\
    vendor/asus/Z010D/proprietary/etc/firmware/wcnss.b11:system/etc/firmware/wcnss.b11\
    vendor/asus/Z010D/proprietary/etc/firmware/wcnss.mdt:system/etc/firmware/wcnss.mdt\
    vendor/asus/Z010D/proprietary/etc/firmware/widevine.b00:system/etc/firmware/widevine.b00\
    vendor/asus/Z010D/proprietary/etc/firmware/widevine.b01:system/etc/firmware/widevine.b01\
    vendor/asus/Z010D/proprietary/etc/firmware/widevine.b02:system/etc/firmware/widevine.b02\
    vendor/asus/Z010D/proprietary/etc/firmware/widevine.b03:system/etc/firmware/widevine.b03\
    vendor/asus/Z010D/proprietary/etc/firmware/widevine.mdt:system/etc/firmware/widevine.mdt\
    vendor/asus/Z010D/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/asus/Z010D/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    vendor/asus/Z010D/proprietary/etc/permissions/com.qti.location.sdk.xml:system/etc/permissions/com.qti.location.sdk.xml \
    vendor/asus/Z010D/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/asus/Z010D/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    vendor/asus/Z010D/proprietary/etc/permissions/ConnectivityExt.xml:system/etc/permissions/ConnectivityExt.xml \
    vendor/asus/Z010D/proprietary/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
    vendor/asus/Z010D/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/asus/Z010D/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/asus/Z010D/proprietary/etc/permissions/qti_telephony_common.xml:system/etc/permissions/qti_telephony_common.xml \
    vendor/asus/Z010D/proprietary/etc/permissions/telephonyservice.xml::system/etc/permissions/telephonyservice.xml \
    vendor/asus/Z010D/proprietary/etc/hostapd/hostapd.accept:system/etc/hostapd/hostapd.accept\
    vendor/asus/Z010D/proprietary/etc/hostapd/hostapd.deny:system/etc/hostapd/hostapd.deny\
    vendor/asus/Z010D/proprietary/etc/hostapd/hostapd_default.conf:system/etc/hostapd/hostapd_default.conf\
    vendor/asus/Z010D/proprietary/etc/wifi/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf\
    vendor/asus/Z010D/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf\
    vendor/asus/Z010D/proprietary/etc/wifi/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf\
    vendor/asus/Z010D/proprietary/etc/icesoundconfig.def:system/etc/icesoundconfig.def\
    vendor/asus/Z010D/proprietary/etc/icesoundpresets.def:system/etc/icesoundpresets.def\
    vendor/asus/Z010D/proprietary/etc/ins_module.sh:system/etc/ins_module.sh\
    vendor/asus/Z010D/proprietary/etc/tamcid:system/etc/tamcid\
    vendor/asus/Z010D/proprietary/etc/thermal-engine-8916.conf:system/etc/thermal-engine-8916.conf\
    vendor/asus/Z010D/proprietary/etc/wfdconfig.xml:system/etc/wfdconfig.xml\
    vendor/asus/Z010D/proprietary/etc/wfdconfigsink.xml:system/etc/wfdconfigsink.xml\
    vendor/asus/Z010D/proprietary/etc/xtra_root_cert.pem:system/etc/xtra_root_cert.pem\
    vendor/asus/Z010D/proprietary/etc/xtwifi.conf:system/etc/xtwifi.conf

PRODUCT_COPY_FILES += \
    vendor/asus/Z010D/proprietary/framework/qcnvitems.jar:system/framework/qcnvitems.jar\
    vendor/asus/Z010D/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar\
    vendor/asus/Z010D/proprietary/framework/org.apache.http.legacy.boot.jar:system/framework/org.apache.http.legacy.boot.jar \
    vendor/asus/Z010D/proprietary/framework/QPerformance.jar:system/framework/QPerformance.jar \
    vendor/asus/Z010D/proprietary/framework/org.cyanogenmod.hardware.jar:system/framework/org.cyanogenmod.hardware.jar \
    vendor/asus/Z010D/proprietary/framework/org.cyanogenmod.platform.jar:system/framework/org.cyanogenmod.platform.jar \
    vendor/asus/Z010D/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar\
    vendor/asus/Z010D/proprietary/framework/com.qti.dpmframework.jar:system/framework/com.qti.dpmframework.jar\
    vendor/asus/Z010D/proprietary/framework/com.qti.location.sdk.jar:system/framework/com.qti.location.sdk.jar\
    vendor/asus/Z010D/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar\
    vendor/asus/Z010D/proprietary/framework/ConnectivityExt.jar:system/framework/ConnectivityExt.jar\
    vendor/asus/Z010D/proprietary/framework/dpmapi.jar:system/framework/dpmapi.jar\
    vendor/asus/Z010D/proprietary/framework/qti-telephony-common.jar:system/framework/qti-telephony-common.jar\
    vendor/asus/Z010D/proprietary/framework/QtiTelephonyServicelibrary.jar:system/framework/QtiTelephonyServicelibrary.jar

PRODUCT_COPY_FILES += \
    vendor/asus/Z010D/proprietary/etc/data/dsi_config.xml:system/etc/data/dsi_config.xml \
    vendor/asus/Z010D/proprietary/etc/data/netmgr_config.xml:system/etc/data/netmgr_config.xml \
    vendor/asus/Z010D/proprietary/etc/data/qmi_config.xml:system/etc/data/qmi_config.xml \
    vendor/asus/Z010D/proprietary/lib/DataSet/ditSCidGen/msgchk.db:system/lib/DataSet/ditSCidGen/msgchk.db \
    vendor/asus/Z010D/proprietary/lib/DataSet/ispDB/ParameterDB.db:system/lib/DataSet/ispDB/ParameterDB.db

PRODUCT_COPY_FILES += \
    vendor/asus/Z010D/proprietary/lib/hw/lights.msm8916.so:system/lib/hw/lights.msm8916.so

PRODUCT_COPY_FILES += \
    vendor/asus/Z010D/proprietary/vendor/bin/audioflacapp:system/vendor/bin/audioflacapp\
    vendor/asus/Z010D/proprietary/vendor/bin/chamomile_provision:system/vendor/bin/chamomile_provision\
    vendor/asus/Z010D/proprietary/vendor/etc/calmodule.cfg:system/vendor/etc/calmodule.cfg\
    vendor/asus/Z010D/proprietary/vendor/etc/fallback_fonts.xml:system/vendor/etc/fallback_fonts.xml\
    vendor/asus/Z010D/proprietary/vendor/etc/style.cng:system/vendor/etc/style.cng\
    vendor/asus/Z010D/proprietary/vendor/etc/workspace_grid_setting.xml:system/vendor/etc/workspace_grid_setting.xml\
    vendor/asus/Z010D/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libasn1cper.so:system/vendor/lib/libasn1cper.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libasn1crt.so:system/vendor/lib/libasn1crt.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libasn1crtx.so:system/vendor/lib/libasn1crtx.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libavenhancements.so:system/vendor/lib/libavenhancements.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libChamomilePA.so:system/vendor/lib/libChamomilePA.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libcne.so:system/vendor/lib/libcne.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libcneconn.so:system/vendor/lib/libcneconn.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libconnctrl.so:system/vendor/lib/libconnctrl.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libdataitems.so:system/vendor/lib/libdataitems.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so\
    vendor/asus/Z010D/proprietary/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libdpmctmgr.so:system/vendor/lib/libdpmctmgr.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libdpmfdmgr.so:system/vendor/lib/libdpmfdmgr.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libdpmframework.so:system/vendor/lib/libdpmframework.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libdpmnsrm.so:system/vendor/lib/libdpmnsrm.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libdpmtcm.so:system/vendor/lib/libdpmtcm.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libEGL_adreno.so:system/vendor/lib/libEGL_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libextendedremotedisplay.so:system/vendor/lib/libextendedremotedisplay.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libFidoCrypto.so:system/vendor/lib/libFidoCrypto.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libFidoCryptoJNI.so:system/vendor/lib/libFidoCryptoJNI.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libFIDOKeyProvisioning.so:system/vendor/lib/libFIDOKeyProvisioning.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libFileMux.so:system/vendor/lib/libFileMux.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libgdtap.so:system/vendor/lib/libgdtap.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libHevcSwDecoder.so:system/vendor/lib/libHevcSwDecoder.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libhwdaphal.so:system/vendor/lib/libhwdaphal.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so\
    vendor/asus/Z010D/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so\
    vendor/asus/Z010D/proprietary/vendor/lib/liblistenjni.so:system/vendor/lib/liblistenjni.so\
    vendor/asus/Z010D/proprietary/vendor/lib/liblistensoundmodel2.so:system/vendor/lib/liblistensoundmodel2.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so\
    vendor/asus/Z010D/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so\
    vendor/asus/Z010D/proprietary/vendor/lib/liblocationservice_glue.so:system/vendor/lib/liblocationservice_glue.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libloc_ext.so:system/vendor/lib/libloc_ext.so\
    vendor/asus/Z010D/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so\
    vendor/asus/Z010D/proprietary/vendor/lib/liblowi_wifihal.so:system/vendor/lib/liblowi_wifihal.so\
    vendor/asus/Z010D/proprietary/vendor/lib/liblowi_wifihal_nl.so:system/vendor/lib/liblowi_wifihal_nl.so\
    vendor/asus/Z010D/proprietary/vendor/lib/liblqe.so:system/vendor/lib/liblqe.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmdsprpc.so:system/vendor/lib/libmdsprpc.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmm-als.so:system/vendor/lib/libmm-als.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmm-disp-apis.so:system/vendor/lib/libmm-disp-apis.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmm-hdcpmgr.so:system/vendor/lib/libmm-hdcpmgr.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmhttpstack.so:system/vendor/lib/libmmhttpstack.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmi.so:system/vendor/lib/libmmi.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmiipstreammmihttp.so:system/vendor/lib/libmmiipstreammmihttp.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmipstreamaal.so:system/vendor/lib/libmmipstreamaal.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmipstreamnetwork.so:system/vendor/lib/libmmipstreamnetwork.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmipstreamsourcehttp.so:system/vendor/lib/libmmipstreamsourcehttp.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmipstreamutils.so:system/vendor/lib/libmmipstreamutils.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmparser_lite.so:system/vendor/lib/libmmparser_lite.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmm-qdcm.so:system/vendor/lib/libmm-qdcm.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmQSM.so:system/vendor/lib/libmmQSM.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmrtpdecoder.so:system/vendor/lib/libmmrtpdecoder.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmrtpencoder.so:system/vendor/lib/libmmrtpencoder.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmwfdinterface.so:system/vendor/lib/libmmwfdinterface.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmwfdsinkinterface.so:system/vendor/lib/libmmwfdsinkinterface.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libmmwfdsrcinterface.so:system/vendor/lib/libmmwfdsrcinterface.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libnative_audio_latency_jni.so:system/vendor/lib/libnative_audio_latency_jni.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so\
    vendor/asus/Z010D/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so\
    vendor/asus/Z010D/proprietary/vendor/lib/liboemcrypto.so:system/vendor/lib/liboemcrypto.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libOmxMux.so:system/vendor/lib/libOmxMux.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libprdrmdecrypt.so:system/vendor/lib/libprdrmdecrypt.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libqct_resampler.so:system/vendor/lib/libqct_resampler.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libqti-at.so:system/vendor/lib/libqti-at.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libQtiTether.so:system/vendor/lib/libQtiTether.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so\
    vendor/asus/Z010D/proprietary/vendor/lib/lib-rcsimssjni.so:system/vendor/lib/lib-rcsimssjni.so\
    vendor/asus/Z010D/proprietary/vendor/lib/lib-rcsjni.so:system/vendor/lib/lib-rcsjni.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libril-qc-radioconfig.so:system/vendor/lib/libril-qc-radioconfig.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so\
    vendor/asus/Z010D/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so\
    vendor/asus/Z010D/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib/lib-rtpcommon.so:system/vendor/lib/lib-rtpcommon.so\
    vendor/asus/Z010D/proprietary/vendor/lib/lib-rtpcore.so:system/vendor/lib/lib-rtpcore.so\
    vendor/asus/Z010D/proprietary/vendor/lib/lib-rtpdaemoninterface.so:system/vendor/lib/lib-rtpdaemoninterface.so\
    vendor/asus/Z010D/proprietary/vendor/lib/lib-rtpsl.so:system/vendor/lib/lib-rtpsl.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libSampleAuthJNI.so:system/vendor/lib/libSampleAuthJNI.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libscve.so:system/vendor/lib/libscve.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libscve_mv.so:system/vendor/lib/libscve_mv.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libsd_sdk_display.so:system/vendor/lib/libsd_sdk_display.so\
    vendor/asus/Z010D/proprietary/vendor/lib/lib-sec-disp.so:system/vendor/lib/lib-sec-disp.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libSecureSampleAuthClient.so:system/vendor/lib/libSecureSampleAuthClient.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libSecureSampleAuthJNI.so:system/vendor/lib/libSecureSampleAuthJNI.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libsecureui.so:system/vendor/lib/libsecureui.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libSecureUILib.so:system/vendor/lib/libSecureUILib.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libsecureuisvc_jni.so:system/vendor/lib/libsecureuisvc_jni.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libsecureui_svcsock.so:system/vendor/lib/libsecureui_svcsock.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libslimclient.so:system/vendor/lib/libslimclient.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libsmwrapper.so:system/vendor/lib/libsmwrapper.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libsregex.so:system/vendor/lib/libsregex.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libsrsprocessing.so:system/vendor/lib/libsrsprocessing.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libStDrvInt.so:system/vendor/lib/libStDrvInt.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libSubSystemShutdown.so:system/vendor/lib/libSubSystemShutdown.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libtar.so:system/vendor/lib/libtar.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libts_detected_face_hal.so:system/vendor/lib/libts_detected_face_hal.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libts_face_beautify_hal.so:system/vendor/lib/libts_face_beautify_hal.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libtzdrmgenprov.so:system/vendor/lib/libtzdrmgenprov.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libtzplayready.so:system/vendor/lib/libtzplayready.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libvcel.so:system/vendor/lib/libvcel.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libvendorconn.so:system/vendor/lib/libvendorconn.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libvoice-svc.so:system/vendor/lib/libvoice-svc.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libwfdcommonutils.so:system/vendor/lib/libwfdcommonutils.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libwfdhdcpcp.so:system/vendor/lib/libwfdhdcpcp.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libwfdmmsink.so:system/vendor/lib/libwfdmmsink.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libwfdmmsrc.so:system/vendor/lib/libwfdmmsrc.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libwfdmmutils.so:system/vendor/lib/libwfdmmutils.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libwfdnative.so:system/vendor/lib/libwfdnative.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libwfdrtsp.so:system/vendor/lib/libwfdrtsp.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libwfdservice.so:system/vendor/lib/libwfdservice.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libwfdsm.so:system/vendor/lib/libwfdsm.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libwfduibcinterface.so:system/vendor/lib/libwfduibcinterface.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libwfduibcsink.so:system/vendor/lib/libwfduibcsink.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libwfduibcsinkinterface.so:system/vendor/lib/libwfduibcsinkinterface.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libwfduibcsrc.so:system/vendor/lib/libwfduibcsrc.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libwfduibcsrcinterface.so:system/vendor/lib/libwfduibcsrcinterface.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libwms.so:system/vendor/lib/libwms.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libwqe.so:system/vendor/lib/libwqe.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libxditk_DIT_MSM8916.so:system/vendor/lib/libxditk_DIT_MSM8916.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libxditk_DIT_Qualcomm.so:system/vendor/lib/libxditk_DIT_Qualcomm.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libxditk_mmcamera2_stats_algorithm.so:system/vendor/lib/libxditk_mmcamera2_stats_algorithm.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libxditk_Network.so:system/vendor/lib/libxditk_Network.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libxt_native.so:system/vendor/lib/libxt_native.so\
    vendor/asus/Z010D/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so\
    vendor/asus/Z010D/proprietary/vendor/lib/drm/libdrmprplugin.so:system/vendor/lib/drm/libdrmprplugin.so\
    vendor/asus/Z010D/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so\
    vendor/asus/Z010D/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so\
    vendor/asus/Z010D/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so\
    vendor/asus/Z010D/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib/egl/libESXEGL_adreno.so:system/vendor/lib/egl/libESXEGL_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib/egl/libESXGLESv1_CM_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib/egl/libESXGLESv2_adreno.so:system/vendor/lib/egl/libESXGLESv2_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so\
    vendor/asus/Z010D/proprietary/vendor/lib/egl/libRBEGL_adreno.so:system/vendor/lib/egl/libRBEGL_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib/egl/libRBGLESv1_CM_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib/egl/libRBGLESv2_adreno.so:system/vendor/lib/egl/libRBGLESv2_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so\
    vendor/asus/Z010D/proprietary/vendor/lib/hw/sound_trigger.primary.msm8916.so:system/vendor/lib/hw/sound_trigger.primary.msm8916.so\
    vendor/asus/Z010D/proprietary/vendor/lib/mediadrm/libprmediadrmdecrypt.so:system/vendor/lib/mediadrm/libprmediadrmdecrypt.so\
    vendor/asus/Z010D/proprietary/vendor/lib/mediadrm/libprmediadrmplugin.so:system/vendor/lib/mediadrm/libprmediadrmplugin.so\
    vendor/asus/Z010D/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so\
    vendor/asus/Z010D/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so\
    vendor/asus/Z010D/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so\
    vendor/asus/Z010D/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libacdb-fts.so:system/vendor/lib64/libacdb-fts.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libacdbloader.so:system/vendor/lib64/libacdbloader.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libacdbmapper.so:system/vendor/lib64/libacdbmapper.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libacdbrtac.so:system/vendor/lib64/libacdbrtac.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libadiertac.so:system/vendor/lib64/libadiertac.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libadreno_utils.so:system/vendor/lib64/libadreno_utils.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libadsprpc.so:system/vendor/lib64/libadsprpc.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libalarmservice_jni.so:system/vendor/lib64/libalarmservice_jni.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libasn1cper.so:system/vendor/lib64/libasn1cper.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libasn1crt.so:system/vendor/lib64/libasn1crt.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libasn1crtx.so:system/vendor/lib64/libasn1crtx.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libaudcal.so:system/vendor/lib64/libaudcal.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libaudioalsa.so:system/vendor/lib64/libaudioalsa.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libavenhancements.so:system/vendor/lib64/libavenhancements.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libbccQTI.so:system/vendor/lib64/libbccQTI.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libbtnv.so:system/vendor/lib64/libbtnv.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libbt-vendor.so:system/vendor/lib64/libbt-vendor.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libc2d30-a3xx.so:system/vendor/lib64/libc2d30-a3xx.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libc2d30-a4xx.so:system/vendor/lib64/libc2d30-a4xx.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libC2D2.so:system/vendor/lib64/libC2D2.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libcalmodule_akm.so:system/vendor/lib64/libcalmodule_akm.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libcalmodule_common.so:system/vendor/lib64/libcalmodule_common.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libcalmodule_gyroscope.so:system/vendor/lib64/libcalmodule_gyroscope.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libCB.so:system/vendor/lib64/libCB.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libChamomilePA.so:system/vendor/lib64/libChamomilePA.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libcne.so:system/vendor/lib64/libcne.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libcneapiclient.so:system/vendor/lib64/libcneapiclient.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libcneconn.so:system/vendor/lib64/libcneconn.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libcneqmiutils.so:system/vendor/lib64/libcneqmiutils.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libCommandSvc.so:system/vendor/lib64/libCommandSvc.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libconfigdb.so:system/vendor/lib64/libconfigdb.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libconnctrl.so:system/vendor/lib64/libconnctrl.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libdataitems.so:system/vendor/lib64/libdataitems.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libdiag.so:system/vendor/lib64/libdiag.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libdisp-aba.so:system/vendor/lib64/libdisp-aba.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/lib-dplmedia.so:system/vendor/lib64/lib-dplmedia.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libdpmctmgr.so:system/vendor/lib64/libdpmctmgr.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libdpmfdmgr.so:system/vendor/lib64/libdpmfdmgr.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libdpmframework.so:system/vendor/lib64/libdpmframework.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libdpmnsrm.so:system/vendor/lib64/libdpmnsrm.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libdpmtcm.so:system/vendor/lib64/libdpmtcm.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libdrmfs.so:system/vendor/lib64/libdrmfs.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libdrmtime.so:system/vendor/lib64/libdrmtime.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libdsi_netctrl.so:system/vendor/lib64/libdsi_netctrl.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libdsutils.so:system/vendor/lib64/libdsutils.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libEGL_adreno.so:system/vendor/lib64/libEGL_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libExtendedExtractor.so:system/vendor/lib64/libExtendedExtractor.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libextendedremotedisplay.so:system/vendor/lib64/libextendedremotedisplay.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libFidoCrypto.so:system/vendor/lib64/libFidoCrypto.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libFidoCryptoJNI.so:system/vendor/lib64/libFidoCryptoJNI.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libFIDOKeyProvisioning.so:system/vendor/lib64/libFIDOKeyProvisioning.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libFileMux.so:system/vendor/lib64/libFileMux.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libFlacSwDec.so:system/vendor/lib64/libFlacSwDec.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libflp.so:system/vendor/lib64/libflp.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libgdtap.so:system/vendor/lib64/libgdtap.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libgeofence.so:system/vendor/lib64/libgeofence.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libgsl.so:system/vendor/lib64/libgsl.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libHevcSwDecoder.so:system/vendor/lib64/libHevcSwDecoder.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libhwdaphal.so:system/vendor/lib64/libhwdaphal.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libidl.so:system/vendor/lib64/libidl.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libizat_core.so:system/vendor/lib64/libizat_core.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/liblbs_core.so:system/vendor/lib64/liblbs_core.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/liblistenjni.so:system/vendor/lib64/liblistenjni.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/liblistensoundmodel2.so:system/vendor/lib64/liblistensoundmodel2.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libllvm-glnext.so:system/vendor/lib64/libllvm-glnext.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libllvm-qcom.so:system/vendor/lib64/libllvm-qcom.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/liblocationservice.so:system/vendor/lib64/liblocationservice.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/liblocationservice_glue.so:system/vendor/lib64/liblocationservice_glue.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libloc_ext.so:system/vendor/lib64/libloc_ext.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libloc_xtra.so:system/vendor/lib64/libloc_xtra.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/liblowi_client.so:system/vendor/lib64/liblowi_client.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/liblowi_wifihal.so:system/vendor/lib64/liblowi_wifihal.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/liblowi_wifihal_nl.so:system/vendor/lib64/liblowi_wifihal_nl.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/liblqe.so:system/vendor/lib64/liblqe.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmdsprpc.so:system/vendor/lib64/libmdsprpc.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmm-abl.so:system/vendor/lib64/libmm-abl.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmm-abl-oem.so:system/vendor/lib64/libmm-abl-oem.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmm-als.so:system/vendor/lib64/libmm-als.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmm-disp-apis.so:system/vendor/lib64/libmm-disp-apis.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmm-hdcpmgr.so:system/vendor/lib64/libmm-hdcpmgr.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmmhttpstack.so:system/vendor/lib64/libmmhttpstack.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmmi.so:system/vendor/lib64/libmmi.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmmiipstreammmihttp.so:system/vendor/lib64/libmmiipstreammmihttp.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmmipstreamaal.so:system/vendor/lib64/libmmipstreamaal.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmmipstreamnetwork.so:system/vendor/lib64/libmmipstreamnetwork.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmmipstreamsourcehttp.so:system/vendor/lib64/libmmipstreamsourcehttp.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmmipstreamutils.so:system/vendor/lib64/libmmipstreamutils.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmmosal.so:system/vendor/lib64/libmmosal.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmmparser.so:system/vendor/lib64/libmmparser.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmmparser_lite.so:system/vendor/lib64/libmmparser_lite.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmm-qdcm.so:system/vendor/lib64/libmm-qdcm.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmmrtpdecoder.so:system/vendor/lib64/libmmrtpdecoder.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmmrtpencoder.so:system/vendor/lib64/libmmrtpencoder.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmmwfdinterface.so:system/vendor/lib64/libmmwfdinterface.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmmwfdsinkinterface.so:system/vendor/lib64/libmmwfdsinkinterface.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libmmwfdsrcinterface.so:system/vendor/lib64/libmmwfdsrcinterface.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libnetmgr.so:system/vendor/lib64/libnetmgr.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libNimsWrap.so:system/vendor/lib64/libNimsWrap.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libOmxAacDec.so:system/vendor/lib64/libOmxAacDec.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libOmxMux.so:system/vendor/lib64/libOmxMux.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libOpenCL.so:system/vendor/lib64/libOpenCL.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libqc-opt.so:system/vendor/lib64/libqc-opt.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libqdi.so:system/vendor/lib64/libqdi.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libqdp.so:system/vendor/lib64/libqdp.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libqmi_cci.so:system/vendor/lib64/libqmi_cci.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libqmi_client_helper.so:system/vendor/lib64/libqmi_client_helper.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libqmi_common_so.so:system/vendor/lib64/libqmi_common_so.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libqmi_csi.so:system/vendor/lib64/libqmi_csi.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libqmi_encdec.so:system/vendor/lib64/libqmi_encdec.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libQSEEComAPI.so:system/vendor/lib64/libQSEEComAPI.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libqti-at.so:system/vendor/lib64/libqti-at.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libqti-perfd-client.so:system/vendor/lib64/libqti-perfd-client.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libQtiTether.so:system/vendor/lib64/libQtiTether.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libquipc_os_api.so:system/vendor/lib64/libquipc_os_api.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/lib-rcsimssjni.so:system/vendor/lib64/lib-rcsimssjni.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/lib-rcsjni.so:system/vendor/lib64/lib-rcsjni.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libril-qc-qmi-1.so:system/vendor/lib64/libril-qc-qmi-1.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libril-qc-radioconfig.so:system/vendor/lib64/libril-qc-radioconfig.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libril-qcril-hook-oem.so:system/vendor/lib64/libril-qcril-hook-oem.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/librpmb.so:system/vendor/lib64/librpmb.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/librs_adreno.so:system/vendor/lib64/librs_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/librs_adreno_sha1.so:system/vendor/lib64/librs_adreno_sha1.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libRSDriver_adreno.so:system/vendor/lib64/libRSDriver_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/lib-rtpcommon.so:system/vendor/lib64/lib-rtpcommon.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/lib-rtpcore.so:system/vendor/lib64/lib-rtpcore.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/lib-rtpdaemoninterface.so:system/vendor/lib64/lib-rtpdaemoninterface.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/lib-rtpsl.so:system/vendor/lib64/lib-rtpsl.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libSampleAuthJNI.so:system/vendor/lib64/libSampleAuthJNI.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libsc-a2xx.so:system/vendor/lib64/libsc-a2xx.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libsc-a3xx.so:system/vendor/lib64/libsc-a3xx.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libscale.so:system/vendor/lib64/libscale.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libsd_sdk_display.so:system/vendor/lib64/libsd_sdk_display.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/lib-sec-disp.so:system/vendor/lib64/lib-sec-disp.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libSecureSampleAuthClient.so:system/vendor/lib64/libSecureSampleAuthClient.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libSecureSampleAuthJNI.so:system/vendor/lib64/libSecureSampleAuthJNI.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libsecureui.so:system/vendor/lib64/libsecureui.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libSecureUILib.so:system/vendor/lib64/libSecureUILib.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libsecureuisvc_jni.so:system/vendor/lib64/libsecureuisvc_jni.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libsecureui_svcsock.so:system/vendor/lib64/libsecureui_svcsock.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libslimclient.so:system/vendor/lib64/libslimclient.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libsmemlog.so:system/vendor/lib64/libsmemlog.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libssd.so:system/vendor/lib64/libssd.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libStDrvInt.so:system/vendor/lib64/libStDrvInt.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libsubsystem_control.so:system/vendor/lib64/libsubsystem_control.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libSubSystemShutdown.so:system/vendor/lib64/libSubSystemShutdown.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libsystem_health_mon.so:system/vendor/lib64/libsystem_health_mon.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libthermalclient.so:system/vendor/lib64/libthermalclient.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libthermalioctl.so:system/vendor/lib64/libthermalioctl.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libtime_genoff.so:system/vendor/lib64/libtime_genoff.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libTimeService.so:system/vendor/lib64/libTimeService.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libtzdrmgenprov.so:system/vendor/lib64/libtzdrmgenprov.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libtzplayready.so:system/vendor/lib64/libtzplayready.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libulp2.so:system/vendor/lib64/libulp2.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libvcel.so:system/vendor/lib64/libvcel.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libvendorconn.so:system/vendor/lib64/libvendorconn.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libvoice-svc.so:system/vendor/lib64/libvoice-svc.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libwfdcommonutils.so:system/vendor/lib64/libwfdcommonutils.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libwfdhdcpcp.so:system/vendor/lib64/libwfdhdcpcp.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libwfdmmsink.so:system/vendor/lib64/libwfdmmsink.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libwfdmmsrc.so:system/vendor/lib64/libwfdmmsrc.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libwfdmmutils.so:system/vendor/lib64/libwfdmmutils.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libwfdnative.so:system/vendor/lib64/libwfdnative.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libwfdrtsp.so:system/vendor/lib64/libwfdrtsp.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libwfdservice.so:system/vendor/lib64/libwfdservice.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libwfdsm.so:system/vendor/lib64/libwfdsm.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libwfduibcinterface.so:system/vendor/lib64/libwfduibcinterface.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libwfduibcsink.so:system/vendor/lib64/libwfduibcsink.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libwfduibcsinkinterface.so:system/vendor/lib64/libwfduibcsinkinterface.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libwfduibcsrc.so:system/vendor/lib64/libwfduibcsrc.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libwfduibcsrcinterface.so:system/vendor/lib64/libwfduibcsrcinterface.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libwms.so:system/vendor/lib64/libwms.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libwqe.so:system/vendor/lib64/libwqe.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libxml.so:system/vendor/lib64/libxml.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libxtadapter.so:system/vendor/lib64/libxtadapter.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libxt_native.so:system/vendor/lib64/libxt_native.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/libxtwifi_ulp_adaptor.so:system/vendor/lib64/libxtwifi_ulp_adaptor.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/egl/eglsubAndroid.so:system/vendor/lib64/egl/eglsubAndroid.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/egl/eglSubDriverAndroid.so:system/vendor/lib64/egl/eglSubDriverAndroid.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/egl/libEGL_adreno.so:system/vendor/lib64/egl/libEGL_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/egl/libESXEGL_adreno.so:system/vendor/lib64/egl/libESXEGL_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib64/egl/libESXGLESv1_CM_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/egl/libESXGLESv2_adreno.so:system/vendor/lib64/egl/libESXGLESv2_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/egl/libGLESv1_CM_adreno.so:system/vendor/lib64/egl/libGLESv1_CM_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/egl/libGLESv2_adreno.so:system/vendor/lib64/egl/libGLESv2_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/egl/libq3dtools_adreno.so:system/vendor/lib64/egl/libq3dtools_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/egl/libQTapGLES.so:system/vendor/lib64/egl/libQTapGLES.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/egl/libRBEGL_adreno.so:system/vendor/lib64/egl/libRBEGL_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib64/egl/libRBGLESv1_CM_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/egl/libRBGLESv2_adreno.so:system/vendor/lib64/egl/libRBGLESv2_adreno.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/hw/flp.default.so:system/vendor/lib64/hw/flp.default.so\
    vendor/asus/Z010D/proprietary/vendor/lib64/mediadrm/libprmediadrmplugin.so:system/vendor/lib64/mediadrm/libprmediadrmplugin.so\
    vendor/asus/Z010D/proprietary/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd\
    vendor/asus/Z010D/proprietary/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd\
    vendor/asus/Z010D/proprietary/vendor/speccfg/carrier_regional_pack_conf.xml:system/vendor/speccfg/carrier_regional_pack_conf.xml
